name: "Build"

on:
  push:
    branches:
      - main
    paths-ignore:
      # - '**/*.md'
      # - '**/*.gitignore'
      # - '**/*.gitattributes'
  pull_request:
    branches:
      - main
    paths-ignore:
      # - '**/*.md'
      # - '**/*.gitignore'
      # - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    # paths-ignore:
    #   - '**/*.md'
    #   - '**/*.gitignore'
    #   - '**/*.gitattributes'
      
jobs:
  test:
    name: testjob
    runs-on: windows-latest
    steps:
    - name: dummy steü
      run: echo "dummy step"
      shell: bash
  build:
    if: false
    name: Build 
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 6.0.x

    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: install nx dependencies
      run: npm install
    
    - name: run custom script
      run: node test.js

    # - name: Build
    #   run: npm run-script build

    # - name: Test
    #   run: npm run-script test